# MySQL Config
spring:
  application:
    name: PinforYou-APIServer
  datasource:
    url: jdbc:mysql://pinforyoudb.online/db
    username: admin
    password: admin1234
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

# AWS S3 (Image Server) Config
cloud:
  aws:
    s3:
      bucket: <버킷이름>
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: <발급받은 accessKey>
      secretKey: <발급받은 secretKey>